apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: atcw0ladx-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-e84cdaff32.r3cv.p3.openshiftapps.com/rhtap/rhtap-qe-python:d78488d458b137eb8de33f447b817c611599ae43@sha256:d78eb577e5a76d866d035fffe5c7080cbdaf68b6458f6c8efdbdbf901ec25948
          name: container-image
